import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { Roboto, Inter, Poppins } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Use `roboto` instead of `inter`
const roboto = Roboto({ subsets: ["latin"], weight: ['100', '300', '400', '500', '700', '900'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="container w-screen h-screen mx-auto flex flex-col justify-between text-myColor">
          <Nav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
